# pylint:disable=line-too-long, too-many-lines
"""CMIS 4.0 memory map"""
CMIS_VER = 4.0

memory_map_rev_4_0 = [
    #  Lower page
    {
        "name": "identifier",
        "page": "lower",
        "byte": 0,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "revision_compliance",
        "page": "lower",
        "byte": 1,
        "len": 1,
        "type": "uint.8",
        "mult": None,
    },
    {
        "name": "flat_mem",
        "page": "lower",
        "byte": 2,
        "len": 1,
        "type": "uint.8",
        "mult": None,
    },
    {
        "name": "module_state",
        "page": "lower",
        "byte": 3,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "bank0_flags",
        "page": "lower",
        "byte": 4,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "bank1_flags",
        "page": "lower",
        "byte": 5,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "bank2_flags",
        "page": "lower",
        "byte": 6,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "bank3_flags",
        "page": "lower",
        "byte": 7,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "module_flag",
        "page": "lower",
        "byte": 8,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "module_alarms",
        "page": "lower",
        "byte": 9,
        "len": 3,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "temperature",
        "page": "lower",
        "byte": 14,
        "len": 2,
        "type": "uint16",
        "mult": 0.00390625,
    },
    {
        "name": "vcc",
        "page": "lower",
        "byte": 16,
        "len": 2,
        "type": "uint16",
        "mult": 100e-6,
    },
    {
        "name": "module_control",
        "page": "lower",
        "byte": 26,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "CDB_status_bank0",
        "page": "lower",
        "byte": 37,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "CDB_status_bank1",
        "page": "lower",
        "byte": 38,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "FW_version",
        "page": "lower",
        "byte": 39,
        "len": 2,
        "type": "uint16",
        "mult": None,
    },
    {
        "name": "application_advertising1",
        "page": "lower",
        "byte": 86,
        "len": 4,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "pw_0",
        "page": "lower",
        "byte": 122,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "pw_1",
        "page": "lower",
        "byte": 123,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "pw_2",
        "page": "lower",
        "byte": 124,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "pw_3",
        "page": "lower",
        "byte": 125,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "bank_select",
        "page": "lower",
        "byte": 126,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "page_select_byte",
        "page": "lower",
        "byte": 127,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    # Page 00h
    {
        "name": "vendor_name",
        "page": 0,
        "byte": 129,
        "len": 16,
        "type": "ascii",
        "mult": None,
    },
    {
        "name": "vendor_oui",
        "page": 0,
        "byte": 145,
        "len": 3,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "part_number",
        "page": 0,
        "byte": 148,
        "len": 16,
        "type": "ascii",
        "mult": None,
    },
    {
        "name": "revision_number",
        "page": 0,
        "byte": 164,
        "len": 2,
        "type": "ascii",
        "mult": None,
    },
    {
        "name": "vendor_serial_number",
        "page": 0,
        "byte": 166,
        "len": 16,
        "type": "ascii",
        "mult": None,
    },
    {
        "name": "mfg_date",
        "page": 0,
        "byte": 182,
        "len": 8,
        "type": "uint8",
        "mult": None,
    },
    # Page 01h
    {
        "name": "DSP_FW_version",
        "page": 1,
        "byte": 194,
        "len": 4,
        "type": "uint32",
        "mult": None,
    },
    # Page 10h
    {
        "name": "data_path_deinit",
        "page": 0x10,
        "byte": 128,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "tx_polarity_flip",
        "page": 0x10,
        "byte": 129,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "tx_disable",
        "page": 0x10,
        "byte": 130,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "tx_squelch_disable",
        "page": 0x10,
        "byte": 131,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "tx_force_squelch",
        "page": 0x10,
        "byte": 132,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "tx_adaptation_freeze",
        "page": 0x10,
        "byte": 134,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "tx_adaptation_store",
        "page": 0x10,
        "byte": 135,
        "len": 2,
        "type": "uint16",
        "mult": None,
    },
    {
        "name": "rx_polarity_flip",
        "page": 0x10,
        "byte": 137,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "rx_disable",
        "page": 0x10,
        "byte": 138,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "rx_squelch_disable",
        "page": 0x10,
        "byte": 139,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "stage_ctrl_set_0",
        "page": 0x10,
        "byte": 143,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_amp_control",
        "page": 0x10,
        "byte": 144,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "app_sel_lane_1",
        "page": 0x10,
        "byte": 145,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "app_sel_lane_2",
        "page": 0x10,
        "byte": 146,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "app_sel_lane_3",
        "page": 0x10,
        "byte": 147,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "app_sel_lane_4",
        "page": 0x10,
        "byte": 148,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "app_sel_lane_5",
        "page": 0x10,
        "byte": 149,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "app_sel_lane_6",
        "page": 0x10,
        "byte": 150,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "app_sel_lane_7",
        "page": 0x10,
        "byte": 151,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "app_sel_lane_8",
        "page": 0x10,
        "byte": 152,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_amp_0",
        "page": 0x10,
        "byte": 162,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_amp_1",
        "page": 0x10,
        "byte": 163,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_amp_2",
        "page": 0x10,
        "byte": 164,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_amp_3",
        "page": 0x10,
        "byte": 165,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_amp_4",
        "page": 0x10,
        "byte": 166,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_amp_5",
        "page": 0x10,
        "byte": 167,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_amp_6",
        "page": 0x10,
        "byte": 168,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_amp_7",
        "page": 0x10,
        "byte": 169,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_amp_8",
        "page": 0x10,
        "byte": 170,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_amp_9",
        "page": 0x10,
        "byte": 171,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_amp_10",
        "page": 0x10,
        "byte": 172,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_amp_11",
        "page": 0x10,
        "byte": 173,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    # Page 11h
    {
        "name": "data_path_state",
        "page": 0x11,
        "byte": 128,
        "len": 4,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "data_path_state_change_flag",
        "page": 0x11,
        "byte": 134,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "tx_fault_flag",
        "page": 0x11,
        "byte": 135,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "tx_los_flag",
        "page": 0x11,
        "byte": 136,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "tx_lol_flag",
        "page": 0x11,
        "byte": 137,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "tx_eq_flag",
        "page": 0x11,
        "byte": 138,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "rx_los_flag",
        "page": 0x11,
        "byte": 147,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "rx_lol_flag",
        "page": 0x11,
        "byte": 148,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "channel1_tx_pwr",
        "page": 0x11,
        "byte": 154,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "channel2_tx_pwr",
        "page": 0x11,
        "byte": 156,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "channel3_tx_pwr",
        "page": 0x11,
        "byte": 158,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "channel4_tx_pwr",
        "page": 0x11,
        "byte": 160,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "channel5_tx_pwr",
        "page": 0x11,
        "byte": 162,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "channel6_tx_pwr",
        "page": 0x11,
        "byte": 164,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "channel7_tx_pwr",
        "page": 0x11,
        "byte": 166,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "channel8_tx_pwr",
        "page": 0x11,
        "byte": 168,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "channel1_tx_bias",
        "page": 0x11,
        "byte": 170,
        "len": 2,
        "type": "uint16",
        "mult": 2.0e-6,
    },
    {
        "name": "channel2_tx_bias",
        "page": 0x11,
        "byte": 172,
        "len": 2,
        "type": "uint16",
        "mult": 2.0e-6,
    },
    {
        "name": "channel3_tx_bias",
        "page": 0x11,
        "byte": 174,
        "len": 2,
        "type": "uint16",
        "mult": 2.0e-6,
    },
    {
        "name": "channel4_tx_bias",
        "page": 0x11,
        "byte": 176,
        "len": 2,
        "type": "uint16",
        "mult": 2.0e-6,
    },
    {
        "name": "channel5_tx_bias",
        "page": 0x11,
        "byte": 178,
        "len": 2,
        "type": "uint16",
        "mult": 2.0e-6,
    },
    {
        "name": "channel6_tx_bias",
        "page": 0x11,
        "byte": 180,
        "len": 2,
        "type": "uint16",
        "mult": 2.0e-6,
    },
    {
        "name": "channel7_tx_bias",
        "page": 0x11,
        "byte": 182,
        "len": 2,
        "type": "uint16",
        "mult": 2.0e-6,
    },
    {
        "name": "channel8_tx_bias",
        "page": 0x11,
        "byte": 184,
        "len": 2,
        "type": "uint16",
        "mult": 2.0e-6,
    },
    {
        "name": "channel1_rx_pwr",
        "page": 0x11,
        "byte": 186,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "channel2_rx_pwr",
        "page": 0x11,
        "byte": 188,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "channel3_rx_pwr",
        "page": 0x11,
        "byte": 190,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "channel4_rx_pwr",
        "page": 0x11,
        "byte": 192,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "channel5_rx_pwr",
        "page": 0x11,
        "byte": 194,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "channel6_rx_pwr",
        "page": 0x11,
        "byte": 196,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "channel7_rx_pwr",
        "page": 0x11,
        "byte": 198,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "channel8_rx_pwr",
        "page": 0x11,
        "byte": 200,
        "len": 2,
        "type": "uint16",
        "mult": 0.1e-6,
    },
    {
        "name": "active_ctrl_lane_1",
        "page": 0x11,
        "byte": 206,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "active_ctrl_lane_2",
        "page": 0x11,
        "byte": 207,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "active_ctrl_lane_3",
        "page": 0x11,
        "byte": 208,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "active_ctrl_lane_4",
        "page": 0x11,
        "byte": 209,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "active_ctrl_lane_5",
        "page": 0x11,
        "byte": 210,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "active_ctrl_lane_6",
        "page": 0x11,
        "byte": 211,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "active_ctrl_lane_7",
        "page": 0x11,
        "byte": 212,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "active_ctrl_lane_8",
        "page": 0x11,
        "byte": 213,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    # page 13h
    {
        "name": "loopback_capability",
        "page": 0x13,
        "byte": 128,
        # read-only reg, only used for debug
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "pattern_capability",
        "page": 0x13,
        "byte": 129,
        # read-only reg, only used for debug
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "diagnostic_capability",
        "page": 0x13,
        "byte": 130,
        # read-only reg, only used for debug
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "pattern_checker_capability",
        "page": 0x13,
        "byte": 131,
        # read-only reg, only used for debug
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_gen_enable",
        "page": 0x13,
        "byte": 144,
        # enable/disable host side generator for 8 lanes; 1'b1 <=> enable
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_gen_inv",
        "page": 0x13,
        "byte": 145,
        # invert host side generator for 8 lanes; 1'b1 <=> invert
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_gen_pre_fec",
        "page": 0x13,
        "byte": 147,
        # define if PRBS is generated before or after FEC; 1'b1 <=> before FEC
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_pattern_select_lane_2_1",
        "page": 0x13,
        "byte": 148,
        # host side PRBS pattern select for tx lane 2 & tx lane 1
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_pattern_select_lane_4_3",
        "page": 0x13,
        "byte": 149,
        # host side PRBS pattern select for tx lane 4 & tx lane 3
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_pattern_select_lane_6_5",
        "page": 0x13,
        "byte": 150,
        # host side PRBS pattern select for tx lane 4 & tx lane 3
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_pattern_select_lane_8_7",
        "page": 0x13,
        "byte": 151,
        # host side PRBS pattern select for tx lane 4 & tx lane 3
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_gen_enable",
        "page": 0x13,
        "byte": 152,
        # enable/disable media side generator for 8 lanes; 1'b1 <=> enable
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_gen_inv",
        "page": 0x13,
        "byte": 153,
        # invert media side generator for 8 lanes; 1'b1 <=> invert
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_gen_pre_fec",
        "page": 0x13,
        "byte": 155,
        # define if PRBS is generated before or after FEC; 1'b1 <=> before FEC
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_pattern_select_lane_2_1",
        "page": 0x13,
        "byte": 156,
        # media side PRBS pattern select for tx lane 2 & tx lane 1
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_pattern_select_lane_4_3",
        "page": 0x13,
        "byte": 157,
        # media side PRBS pattern select for tx lane 2 & tx lane 1
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_pattern_select_lane_6_5",
        "page": 0x13,
        "byte": 158,
        # media side PRBS pattern select for tx lane 2 & tx lane 1
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_pattern_select_lane_8_7",
        "page": 0x13,
        "byte": 159,
        # media side PRBS pattern select for tx lane 2 & tx lane 1
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_checker_enable",
        "page": 0x13,
        "byte": 160,
        # enable/disable host side checker for 8 lanes; 1'b1 <=> enable
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_checker_inv",
        "page": 0x13,
        "byte": 161,
        # invert host side checker for 8 lanes; 1'b1 <=> invert
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_checker_post_fec",
        "page": 0x13,
        "byte": 163,
        # define if BER is checked before or after FEC; 1'b1 <=> after FEC
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_checker_pattern_select_lane_2_1",
        "page": 0x13,
        "byte": 164,
        # host side BER pattern select for tx lane 2 & tx lane 1
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_checker_pattern_select_lane_4_3",
        "page": 0x13,
        "byte": 165,
        # host side BER pattern select for tx lane 2 & tx lane 1
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_checker_pattern_select_lane_6_5",
        "page": 0x13,
        "byte": 166,
        # host side BER pattern select for tx lane 2 & tx lane 1
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_checker_pattern_select_lane_8_7",
        "page": 0x13,
        "byte": 167,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_checker_enable",
        "page": 0x13,
        "byte": 168,
        # enable/disable media checker for 8 lanes; 1'b1 <=> enable
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_checker_inv",
        "page": 0x13,
        "byte": 169,
        # invert media checker for 8 lanes; 1'b1 <=> invert
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_checker_post_fec",
        "page": 0x13,
        "byte": 171,
        # define if BER is checked before or after FEC; 1'b1 <=> after FEC
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_checker_pattern_select_lane_2_1",
        "page": 0x13,
        "byte": 172,
        # media BER .pattern select for tx lane 2 & tx lane 1
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_checker_pattern_select_lane_4_3",
        "page": 0x13,
        "byte": 173,
        # media BER pattern select for tx lane 4 & tx lane 3
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_checker_pattern_select_lane_6_5",
        "page": 0x13,
        "byte": 174,
        # media BER .pattern select for tx lane 6 & tx lane 5
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_checker_pattern_select_lane_8_7",
        "page": 0x13,
        "byte": 175,
        # media BER pattern select for tx lane 8 & tx lane 7
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "ref_clk_ctrl",
        "page": 0x13,
        "byte": 176,
        # specifying the generator/checker should use
        # reference/recovered clock
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "ber_ctrl",
        "page": 0x13,
        "byte": 177,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_near_LB_en",
        "page": 0x13,
        "byte": 183,
        # enable host near-end loopback for all 8 lanes;
        # 1'b1 <=> loopback mode
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_near_LB_en",
        "page": 0x13,
        "byte": 181,
        # enable media near-end loopback for all 8 lanes;
        # 1'b1 <=> loopback mode
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_far_LB_en",
        "page": 0x13,
        "byte": 182,
        # enable host. far-end loopback for all 8 lanes;
        # 1'b1 <=> loopback mode
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_far_LB_en",
        "page": 0x13,
        "byte": 180,
        # enable media far-end loopback for all 8 lanes;
        # 1'b1 <=> loopback mode
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "ref_clk_loss",
        "page": 0x13,
        "byte": 206,
        # bit 7: 1'b1 <=> reference clock lost
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_checker_gating_complete",
        "page": 0x13,
        "byte": 208,
        # read only reg for debug purpose
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_checker_gating_complete",
        "page": 0x13,
        "byte": 209,
        # read only reg for debug purpose
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_PPG_LOL",
        "page": 0x13,
        "byte": 210,
        # read only reg for debug purpose
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_PPG_LOL",
        "page": 0x13,
        "byte": 211,
        # read only reg for debug purpose
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_BERT_LOL",
        "page": 0x13,
        "byte": 212,
        # read only reg for debug purpose
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_BERT_LOL",
        "page": 0x13,
        "byte": 213,
        # read only reg for debug purpose
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    # page 14h
    {
        "name": "diag_SEL",
        "page": 0x14,
        "byte": 128,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_lane_gen_lol",
        "page": 0x14,
        "byte": 136,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_lane_gen_lol",
        "page": 0x14,
        "byte": 137,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_lane_checker_lol",
        "page": 0x14,
        "byte": 138,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "media_lane_checker_lol",
        "page": 0x14,
        "byte": 139,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "host_BER_lane_1",
        "page": 0x14,
        "byte": 192,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "host_BER_lane_2",
        "page": 0x14,
        "byte": 194,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "host_BER_lane_3",
        "page": 0x14,
        "byte": 196,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "host_BER_lane_4",
        "page": 0x14,
        "byte": 198,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "host_BER_lane_5",
        "page": 0x14,
        "byte": 200,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "host_BER_lane_6",
        "page": 0x14,
        "byte": 202,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "host_BER_lane_7",
        "page": 0x14,
        "byte": 204,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "host_BER_lane_8",
        "page": 0x14,
        "byte": 206,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "media_BER_lane_1",
        "page": 0x14,
        "byte": 208,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "media_BER_lane_2",
        "page": 0x14,
        "byte": 210,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "media_BER_lane_3",
        "page": 0x14,
        "byte": 212,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "media_BER_lane_4",
        "page": 0x14,
        "byte": 214,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "media_BER_lane_5",
        "page": 0x14,
        "byte": 216,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "media_BER_lane_6",
        "page": 0x14,
        "byte": 218,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "media_BER_lane_7",
        "page": 0x14,
        "byte": 220,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "media_BER_lane_8",
        "page": 0x14,
        "byte": 222,
        "len": 2,
        "type": "F16",
        "mult": None,
    },
    {
        "name": "err_cnt_lane_1",
        "page": 0x14,
        "byte": 192,
        "len": 8,
        "type": "uint64-LE",
        "mult": None,
    },
    {
        "name": "bit_cnt_lane_1",
        "page": 0x14,
        "byte": 200,
        "len": 8,
        "type": "uint64-LE",
        "mult": None,
    },
    {
        "name": "err_cnt_lane_2",
        "page": 0x14,
        "byte": 208,
        "len": 8,
        "type": "uint64-LE",
        "mult": None,
    },
    {
        "name": "bit_cnt_lane_2",
        "page": 0x14,
        "byte": 216,
        "len": 8,
        "type": "uint64-LE",
        "mult": None,
    },
    {
        "name": "err_cnt_lane_3",
        "page": 0x14,
        "byte": 224,
        "len": 8,
        "type": "uint64-LE",
        "mult": None,
    },
    {
        "name": "bit_cnt_lane_3",
        "page": 0x14,
        "byte": 232,
        "len": 8,
        "type": "uint64-LE",
        "mult": None,
    },
    {
        "name": "err_cnt_lane_4",
        "page": 0x14,
        "byte": 240,
        "len": 8,
        "type": "uint64-LE",
        "mult": None,
    },
    {
        "name": "bit_cnt_lane_4",
        "page": 0x14,
        "byte": 248,
        "len": 8,
        "type": "uint64-LE",
        "mult": None,
    },
    {
        "name": "host_SNR_lane_1",
        "page": 0x14,
        "byte": 208,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    {
        "name": "host_SNR_lane_2",
        "page": 0x14,
        "byte": 210,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    {
        "name": "host_SNR_lane_3",
        "page": 0x14,
        "byte": 212,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    {
        "name": "host_SNR_lane_4",
        "page": 0x14,
        "byte": 214,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    {
        "name": "host_SNR_lane_5",
        "page": 0x14,
        "byte": 216,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    {
        "name": "host_SNR_lane_6",
        "page": 0x14,
        "byte": 218,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    {
        "name": "host_SNR_lane_7",
        "page": 0x14,
        "byte": 220,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    {
        "name": "host_SNR_lane_8",
        "page": 0x14,
        "byte": 222,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    {
        "name": "media_SNR_lane_1",
        "page": 0x14,
        "byte": 240,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    {
        "name": "media_SNR_lane_2",
        "page": 0x14,
        "byte": 242,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    {
        "name": "media_SNR_lane_3",
        "page": 0x14,
        "byte": 244,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    {
        "name": "media_SNR_lane_4",
        "page": 0x14,
        "byte": 246,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    {
        "name": "media_SNR_lane_5",
        "page": 0x14,
        "byte": 248,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    {
        "name": "media_SNR_lane_6",
        "page": 0x14,
        "byte": 250,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    {
        "name": "media_SNR_lane_7",
        "page": 0x14,
        "byte": 252,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    {
        "name": "media_SNR_lane_8",
        "page": 0x14,
        "byte": 254,
        "len": 2,
        "type": "uint16-LE",
        "mult": None,
    },
    # 9Fh
    {
        "name": "CDB_MSB",
        "page": 0x9F,
        "byte": 128,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "CDB_LSB",
        "page": 0x9F,
        "byte": 129,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "CDB_EPL_len_0",
        "page": 0x9F,
        "byte": 130,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "CDB_EPL_len_1",
        "page": 0x9F,
        "byte": 131,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "CDB_LPL_len",
        "page": 0x9F,
        "byte": 132,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "CDB_checksum",
        "page": 0x9F,
        "byte": 133,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "CDB_RLPL_len",
        "page": 0x9F,
        "byte": 134,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "CDB_RLPL_checksum",
        "page": 0x9F,
        "byte": 135,
        "len": 1,
        "type": "uint8",
        "mult": None,
    },
    {
        "name": "CDB_LPL",
        "page": 0x9F,
        "byte": 136,
        "len": 120,
        "type": "uint8",
        "mult": None,
    },
]
